name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *' # 每小时执行一次

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: 'main' # 您想要同步的分支

    - name: Fetch Upstream
      run: |
        git remote add upstream https://github.com/lobehub/lobe-chat.git
        git fetch upstream

    - name: Merge Upstream Changes
      run: |
        git merge --allow-unrelated-histories upstream/main # 如果不是 'main' 分支，请替换为您想要同步的分支
