name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *' # 每小时执行一次

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: 'main' # 您想要同步的分支

    - name: Fetch Upstream
      run: |
        git remote add upstream https://github.com/lobehub/lobe-chat.git
        git fetch upstream

    - name: Merge Upstream Changes
      run: |
        git config --global user.email "lichengzhibenrende@outlook.com"
        git config --global user.name "lichengzhidegithub"
        git merge --allow-unrelated-histories --strategy=ours upstream/main
